async function Module(moduleArg={}){var moduleRtn;var h=moduleArg,aa="object"==typeof window,k="undefined"!=typeof WorkerGlobalScope,l=k&&self.name?.startsWith("em-pthread");h.listenFish=void 0;h.listenZero=void 0;h.zero=a=>ba(a,!1);h.fish=a=>ba(a,!0);h.setZeroWeights=a=>{const b=fa(a.byteLength);if(!b)throw Error(`Could not allocate ${a.byteLength} bytes`);h.HEAPU8.set(a,b);ha(b,a.byteLength)};h.print=a=>{a.startsWith("zero:")?h.listenZero?.(a.slice(5)):a.startsWith("fish:")?h.listenFish?.(a.slice(5)):console.info(a)};h.printErr=a=>console.error(a);
function ba(a,b){const c=q(a)+1,d=fa(c);if(!d)throw Error(`Could not allocate ${c} bytes`);r(a,t,d,c);ia(d,b);ja(d)}var ka=[],la=import.meta.url,ma="",na,oa;if(aa||k){try{ma=(new URL(".",la)).href}catch{}k&&(oa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});na=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}
var pa=console.log.bind(console),u=console.error.bind(console),w,qa=!1,x,ra,sa,ta;
if(l){var ua=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.pa;if("load"===d){let e=[];self.onmessage=f=>e.push(f);ta=()=>{postMessage({pa:"loaded"});for(let f of e)a(f);self.onmessage=a};for(const f of c.bb)if(!h[f]||h[f].proxy)h[f]=(...g)=>{postMessage({pa:"callHandler",ab:f,Za:g})},"print"==f&&(pa=h[f]),"printErr"==f&&(u=h[f]);y=c.nb;va();w=c.ob;wa();xa()}else if("run"===d){ya(c.na);za(c.na,0,0,1,0,0);Aa();Ba(c.na);ua||=!0;try{Ca(c.kb,c.Ha)}catch(e){if("unwind"!=
e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?ua&&Da():d&&(u(`worker: received unknown command ${d}`),u(c)))}catch(e){throw Ea(),e;}}self.onmessage=a}var y,z,t,Fa,A,B,Ga,E,Ha=!1,Ia=!1;function va(){var a=y.buffer;z=new Int8Array(a);Fa=new Int16Array(a);h.HEAPU8=t=new Uint8Array(a);new Uint16Array(a);A=new Int32Array(a);B=new Uint32Array(a);new Float32Array(a);Ga=new Float64Array(a);E=new BigInt64Array(a);new BigUint64Array(a)}
function Ja(){Ha=!0;l?ta():(h.noFSInit||Ka||(Ka=!0,La("/dev/tty","/dev/stdin"),La("/dev/tty","/dev/stdout"),La("/dev/tty1","/dev/stderr"),Ma("/dev/stdin",0),Ma("/dev/stdout",1),Ma("/dev/stderr",1)),F.I(),Na=!1)}function G(a){a="Aborted("+a+")";u(a);qa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");sa?.(a);throw a;}var Oa;
async function Qa(a){try{var b=await na(a);return new Uint8Array(b)}catch{}if(oa)a=oa(a);else throw"both async and sync fetching of the wasm failed";return a}async function Ra(a,b){try{var c=await Qa(a);return await WebAssembly.instantiate(c,b)}catch(d){u(`failed to asynchronously prepare wasm: ${d}`),G(d)}}
async function Sa(a){var b=Oa;try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){u(`wasm streaming compile failed: ${d}`),u("falling back to ArrayBuffer instantiation")}return Ra(b,a)}function Ta(){Ua={b:Va,D:Wa,g:Xa,w:Ya,x:Za,y:$a,k:ab,C:bb,F:cb,o:db,h:eb,j:Ba,e:fb,G:gb,p:hb,H:ib,E:jb,i:kb,l:lb,q:mb,c:nb,B:ob,m:pb,s:qb,t:rb,d:sb,f:tb,v:ub,u:vb,A:wb,z:xb,a:y,n:yb,r:zb};return{a:Ua}}
async function wa(){function a(c,d){F=c.exports;Ab.push(F.Q);Bb=F.S;w=d;c=F;h._malloc=fa=c.J;h._free=ja=c.K;Cb=c.L;h._main=c.M;h._uci=ia=c.N;h._set_weights=ha=c.O;h._quit=c.P;h.__emscripten_proxy_main=Db=c.R;Eb=c.T;za=c.U;Ea=c.V;Fb=c.W;Gb=c.X;Hb=c.Y;Ib=c.Z;Jb=c._;Kb=c.$;Lb=c.aa;Mb=c.ba;Nb=c.ca;Ob=c.da;return F}var b=Ta();if(l)return b=new WebAssembly.Instance(w,Ta()),a(b,w);Oa??=h.locateFile?h.locateFile?h.locateFile("zerofishEngine.wasm",ma):ma+"zerofishEngine.wasm":(new URL("zerofishEngine.wasm",
import.meta.url)).href;return function(c){return a(c.instance,c.module)}(await Sa(b))}class Pb{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Qb=a=>{a.terminate();a.onmessage=()=>{}},Rb=[],Tb=a=>{if(0==H.length){if(h.mainScriptUrlOrBlob){var b=h.mainScriptUrlOrBlob;"string"!=typeof b&&(b=URL.createObjectURL(b));b=new Worker(b,{type:"module",name:"em-pthread"})}else b=new Worker(new URL("zerofishEngine.js",import.meta.url),{type:"module",name:"em-pthread"});H.push(b);Sb()}b=H.pop();if(!b)return 6;I.push(b);J[a.na]=b;b.na=a.na;b.postMessage({pa:"run",kb:a.jb,Ha:a.Ha,na:a.na},a.Xa);return 0},K=0,pb=()=>0<K,L=(a,b,...c)=>{for(var d=
2*c.length,e=Ob(),f=Nb(8*d),g=f>>3,m=0;m<c.length;m++){var p=c[m];"bigint"==typeof p?(E[g+2*m]=1n,E[g+2*m+1]=p):(E[g+2*m]=0n,Ga[g+2*m+1]=p)}a=Gb(a,0,d,f,b);Mb(e);return a};function yb(a){if(l)return L(0,1,a);x=a;0<K||(Ub(),qa=!0);throw new Pb(a);}function Vb(a){if(l)return L(1,0,a);--K;sb(a)}
var sb=a=>{x=a;if(l)throw Vb(a),"unwind";if(!(0<K||l)){Eb();Ka=!1;Fb(0);for(var b of M)b&&Wb(b);Ub();Ia=!0}yb(a)},H=[],I=[],Ab=[],J={},Ub=()=>{for(var a of I)Qb(a);for(a of H)Qb(a);H=[];I=[];J={}},Xb=a=>{var b=a.na;delete J[b];H.push(a);I.splice(I.indexOf(a),1);a.na=0;Hb(b)};function Aa(){Ab.forEach(a=>a())}
var Sb=()=>{var a=H[0];new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.pa;if(g.Ga&&g.Ga!=Cb()){var m=J[g.Ga];m?m.postMessage(g,g.Xa):u(`Internal error! Worker sent a message "${f}" to target pthread ${g.Ga}, but that thread no longer exists!`)}else if("checkMailbox"===f)Da();else if("spawnThread"===f)Tb(g);else if("cleanupThread"===f)Yb(()=>{Xb(J[g.lb])});else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===f)h[g.ab](...g.Za);else f&&u(`worker sent an unknown command ${f}`)};
a.onerror=f=>{u(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({pa:"load",bb:c,nb:y,ob:w})})};function ya(a){var b=B[a+52>>2];Lb(b,b-B[a+56>>2]);Mb(b)}var Zb=[],Bb,Ca=(a,b)=>{K=0;var c=Zb[a];c||(Zb[a]=c=Bb.get(a));a=c(b);0<K?x=a:Ib(a)};class $b{constructor(a){this.Da=a-24}}
var ac=0,bc=0,Va=(a,b,c)=>{var d=new $b(a);B[d.Da+16>>2]=0;B[d.Da+4>>2]=b;B[d.Da+8>>2]=c;ac=a;bc++;throw ac;};function cc(a,b,c,d){return l?L(2,1,a,b,c,d):Wa(a,b,c,d)}
var Wa=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return 6;var e=[];if(l&&0===e.length)return cc(a,b,c,d);a={jb:c,na:a,Ha:d,Xa:e};return l?(a.pa="spawnThread",postMessage(a,e),0):Tb(a)},P=()=>{var a=A[+O>>2];O+=4;return a},dc=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},ec=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=dc(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},fc=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},gc=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),hc=a=>{(hc=gc())(a)},ic=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=
dc(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},jc="undefined"!=typeof TextDecoder?new TextDecoder:void 0,Q=(a,b=0)=>{var c=b;for(var d=c+void 0;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&jc)return jc.decode(a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):
(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},kc=[],q=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},r=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>
6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},lc=[];function mc(a,b){lc[a]={input:[],output:[],sa:b};nc(a,oc)}
var oc={open(a){var b=lc[a.node.Ea];if(!b)throw new R(43);a.ha=b;a.seekable=!1},close(a){a.ha.sa.Aa(a.ha)},Aa(a){a.ha.sa.Aa(a.ha)},read(a,b,c,d){if(!a.ha||!a.ha.sa.Qa)throw new R(60);for(var e=0,f=0;f<d;f++){try{var g=a.ha.sa.Qa(a.ha)}catch(m){throw new R(29);}if(void 0===g&&0===e)throw new R(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.va=Date.now());return e},write(a,b,c,d){if(!a.ha||!a.ha.sa.Ma)throw new R(60);try{for(var e=0;e<d;e++)a.ha.sa.Ma(a.ha,b[c+e])}catch(f){throw new R(29);
}d&&(a.node.ka=a.node.ja=Date.now());return e}},pc={Qa(){a:{if(!kc.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(q(a)+1);a=r(a,b,0,b.length);b.length=a;kc=b}b=kc.shift()}return b},Ma(a,b){null===b||10===b?(pa(Q(a.output)),a.output=[]):0!=b&&a.output.push(b)},Aa(a){0<a.output?.length&&(pa(Q(a.output)),a.output=[])},eb(){return{ub:25856,wb:5,tb:191,vb:35387,sb:[3,28,127,21,4,0,1,0,17,
19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},fb(){return 0},gb(){return[24,80]}},qc={Ma(a,b){null===b||10===b?(u(Q(a.output)),a.output=[]):0!=b&&a.output.push(b)},Aa(a){0<a.output?.length&&(u(Q(a.output)),a.output=[])}},T={ma:null,ra(){return T.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new R(63);T.ma||(T.ma={dir:{node:{ua:T.ga.ua,oa:T.ga.oa,xa:T.ga.xa,Ba:T.ga.Ba,Va:T.ga.Va,Ya:T.ga.Ya,Wa:T.ga.Wa,Na:T.ga.Na,Fa:T.ga.Fa},stream:{la:T.ea.la}},
file:{node:{ua:T.ga.ua,oa:T.ga.oa},stream:{la:T.ea.la,read:T.ea.read,write:T.ea.write,Sa:T.ea.Sa,Ua:T.ea.Ua}},link:{node:{ua:T.ga.ua,oa:T.ga.oa,ya:T.ga.ya},stream:{}},Pa:{node:{ua:T.ga.ua,oa:T.ga.oa},stream:rc}});c=sc(a,b,c,d);16384===(c.mode&61440)?(c.ga=T.ma.dir.node,c.ea=T.ma.dir.stream,c.fa={}):32768===(c.mode&61440)?(c.ga=T.ma.file.node,c.ea=T.ma.file.stream,c.ia=0,c.fa=null):40960===(c.mode&61440)?(c.ga=T.ma.link.node,c.ea=T.ma.link.stream):8192===(c.mode&61440)&&(c.ga=T.ma.Pa.node,c.ea=T.ma.Pa.stream);
c.va=c.ka=c.ja=Date.now();a&&(a.fa[b]=c,a.va=a.ka=a.ja=c.va);return c},Ab(a){return a.fa?a.fa.subarray?a.fa.subarray(0,a.ia):new Uint8Array(a.fa):new Uint8Array(0)},ga:{ua(a){var b={};b.xb=8192===(a.mode&61440)?a.id:1;b.Cb=a.id;b.mode=a.mode;b.Db=1;b.uid=0;b.Bb=0;b.Ea=a.Ea;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ia:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.va=new Date(a.va);b.ka=new Date(a.ka);b.ja=new Date(a.ja);b.$a=4096;b.rb=Math.ceil(b.size/b.$a);return b},
oa(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.ia!=b&&(0==b?(a.fa=null,a.ia=0):(c=a.fa,a.fa=new Uint8Array(b),c&&a.fa.set(c.subarray(0,Math.min(b,a.ia))),a.ia=b)))},xa(){T.Ia||(T.Ia=new R(44),T.Ia.stack="<generic error, no stack>");throw T.Ia;},Ba(a,b,c,d){return T.createNode(a,b,c,d)},Va(a,b,c){try{var d=tc(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.fa)throw new R(55);e=uc(d.parent.id,d.name);if(U[e]===d)U[e]=d.wa;else for(e=
U[e];e;){if(e.wa===d){e.wa=d.wa;break}e=e.wa}}delete a.parent.fa[a.name];b.fa[c]=a;a.name=c;b.ja=b.ka=a.parent.ja=a.parent.ka=Date.now()},Ya(a,b){delete a.fa[b];a.ja=a.ka=Date.now()},Wa(a,b){var c=tc(a,b),d;for(d in c.fa)throw new R(55);delete a.fa[b];a.ja=a.ka=Date.now()},Na(a){return[".","..",...Object.keys(a.fa)]},Fa(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},ya(a){if(40960!==(a.mode&61440))throw new R(28);return a.link}},ea:{read(a,b,c,d,e){var f=a.node.fa;if(e>=a.node.ia)return 0;
a=Math.min(a.node.ia-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.ka=a.ja=Date.now();if(b.subarray&&(!a.fa||a.fa.subarray)){if(f)return a.fa=b.subarray(c,c+d),a.ia=d;if(0===a.ia&&0===e)return a.fa=b.slice(c,c+d),a.ia=d;if(e+d<=a.ia)return a.fa.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.fa?a.fa.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.fa,a.fa=new Uint8Array(f),
0<a.ia&&a.fa.set(g.subarray(0,a.ia),0));if(a.fa.subarray&&b.subarray)a.fa.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.fa[e+f]=b[c+f];a.ia=Math.max(a.ia,e+d);return d},la(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ia);if(0>b)throw new R(28);return b},Sa(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new R(43);a=a.node.fa;if(e&2||!a||a.buffer!==z.buffer){d=!0;G();e=void 0;if(!e)throw new R(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);z.set(a,e)}}else d=!1,e=a.byteOffset;return{Da:e,qb:d}},Ua(a,b,c,d){T.ea.write(a,b,0,d,c,!1);return 0}}},vc=a=>{var b=0;a&&(b|=365);return b},wc=0,xc=null,yc={},M=[],zc=1,U=null,Ka=!1,Na=!0,R=class{name="ErrnoError";constructor(a){this.qa=a}},Ac=class{za={};node=null;get flags(){return this.za.flags}set flags(a){this.za.flags=a}get position(){return this.za.position}set position(a){this.za.position=a}},Bc=class{ga={};ea={};Ca=null;constructor(a,b,c,d){a||=this;this.parent=a;this.ra=a.ra;this.id=
zc++;this.name=b;this.mode=c;this.Ea=d;this.va=this.ka=this.ja=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function V(a,b={}){if(!a)throw new R(44);b.Ka??(b.Ka=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(m=>!!m);for(var d=xc,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=fc(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=ec(e+"/"+a[f]);try{d=tc(d,a[f])}catch(m){if(44===m?.qa&&g&&b.ib)return{path:e};throw m;}!d.Ca||g&&!b.Ka||(d=d.Ca.root);if(40960===(d.mode&61440)&&(!g||b.Ja)){if(!d.ga.ya)throw new R(52);
d=d.ga.ya(d);"/"===d.charAt(0)||(d=fc(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new R(32);}function uc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%U.length}function tc(a,b){var c=16384===(a.mode&61440)?(c=Cc(a,"x"))?c:a.ga.xa?0:2:54;if(c)throw new R(c);for(c=U[uc(a.id,b)];c;c=c.wa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ga.xa(a,b)}
function sc(a,b,c,d){a=new Bc(a,b,c,d);b=uc(a.parent.id,a.name);a.wa=U[b];return U[b]=a}function Dc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Cc(a,b){if(Na)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ec(a,b){if(16384!==(a.mode&61440))return 54;try{return tc(a,b),20}catch(c){}return Cc(a,"wx")}function W(a){a=M[a];if(!a)throw new R(8);return a}
function Fc(a,b=-1){a=Object.assign(new Ac,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!M[b])break a;throw new R(33);}a.ta=b;return M[b]=a}function Gc(a,b=-1){a=Fc(a,b);a.ea?.zb?.(a);return a}function Hc(a,b){var c=null?.ea.oa,d=c?null:a;c??=a.ga.oa;if(!c)throw new R(63);c(d,b)}var rc={open(a){a.ea=yc[a.node.Ea].ea;a.ea.open?.(a)},la(){throw new R(70);}};function nc(a,b){yc[a]={ea:b}}
function Ic(a,b){var c="/"===b;if(c&&xc)throw new R(10);if(!c&&b){var d=V(b,{Ka:!1});b=d.path;d=d.node;if(d.Ca)throw new R(10);if(16384!==(d.mode&61440))throw new R(54);}b={type:a,Eb:{},Ta:b,hb:[]};a=a.ra(b);a.ra=b;b.root=a;c?xc=a:d&&(d.Ca=b,d.ra&&d.ra.hb.push(b))}function Jc(a,b,c){var d=V(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new R(28);if("."===a||".."===a)throw new R(20);var e=Ec(d,a);if(e)throw new R(e);if(!d.ga.Ba)throw new R(63);return d.ga.Ba(d,a,b,c)}
function X(a){return Jc(a,16895,0)}function Kc(a,b,c){"undefined"==typeof c&&(c=b,b=438);Jc(a,b|8192,c)}function La(a,b){if(!ic(a))throw new R(44);var c=V(b,{parent:!0}).node;if(!c)throw new R(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Ec(c,b);if(d)throw new R(d);if(!c.ga.Fa)throw new R(63);c.ga.Fa(c,b,a)}
function Ma(a,b,c=438){if(""===a)throw new R(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var f=V(a,{Ja:!(b&131072),ib:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new R(20);}else{if(e)throw new R(31);d=Jc(a,c|511,0);f=!0}if(!d)throw new R(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&
61440))throw new R(54);if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==Dc(b)||b&576)?31:Cc(d,Dc(b)):44))throw new R(e);if(b&512&&!f){e=d;e="string"==typeof e?V(e,{Ja:!0}).node:e;if(16384===(e.mode&61440))throw new R(31);if(32768!==(e.mode&61440))throw new R(28);if(a=Cc(e,"w"))throw new R(a);Hc(e,{size:0,timestamp:Date.now()})}a:for(e=d;;){if(e===e.parent){e=e.ra.Ta;var g=g?"/"!==e[e.length-1]?`${e}/${g}`:e+g:e;break a}g=g?`${e.name}/${g}`:e.name;e=e.parent}b=Fc({node:d,path:g,
flags:b&-131713,seekable:!0,position:0,ea:d.ea,mb:[],error:!1});b.ea.open&&b.ea.open(b);f&&(c&=511,d="string"==typeof d?V(d,{Ja:!0}).node:d,Hc(d,{mode:c&4095|d.mode&-4096,ja:Date.now(),yb:void 0}));return b}function Wb(a){if(null===a.ta)throw new R(8);a.La&&(a.La=null);try{a.ea.close&&a.ea.close(a)}catch(b){throw b;}finally{M[a.ta]=null}a.ta=null}
function Lc(a,b,c){if(null===a.ta)throw new R(8);if(!a.seekable||!a.ea.la)throw new R(70);if(0!=c&&1!=c&&2!=c)throw new R(28);a.position=a.ea.la(a,b,c);a.mb=[]}
function Y(a,b){a=ec("/dev/"+a);var c=vc(!!b);Y.Ra??(Y.Ra=64);var d=Y.Ra++<<8|0;nc(d,{open(e){e.seekable=!1},close(){(void 0)?.buffer?.length&&(void 0)(10)},read(e,f,g,m){for(var p=0,n=0;n<m;n++){try{var v=b()}catch(S){throw new R(29);}if(void 0===v&&0===p)throw new R(6);if(null===v||void 0===v)break;p++;f[g+n]=v}p&&(e.node.va=Date.now());return p},write(e,f,g,m){for(var p=0;p<m;p++)try{(void 0)(f[g+p])}catch(n){throw new R(29);}m&&(e.node.ka=e.node.ja=Date.now());return p}});Kc(a,c,d)}
var Z={},O=void 0;function Xa(a,b,c){if(l)return L(3,1,a,b,c);O=c;try{var d=W(a);switch(b){case 0:var e=P();if(0>e)break;for(;M[e];)e++;return Gc(d,e).ta;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=P(),d.flags|=e,0;case 12:return e=P(),Fa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof Z||"ErrnoError"!==f.name)throw f;return-f.qa}}
function Ya(a,b,c){if(l)return L(4,1,a,b,c);O=c;try{var d=W(a);switch(b){case 21509:return d.ha?0:-59;case 21505:if(!d.ha)return-59;if(d.ha.sa.eb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=P();A[e>>2]=25856;A[e+4>>2]=5;A[e+8>>2]=191;A[e+12>>2]=35387;for(var f=0;32>f;f++)z[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.ha?0:-59;case 21506:case 21507:case 21508:if(!d.ha)return-59;if(d.ha.sa.fb)for(e=P(),a=[],f=0;32>f;f++)a.push(z[e+f+17]);
return 0;case 21519:if(!d.ha)return-59;e=P();return A[e>>2]=0;case 21520:return d.ha?-28:-59;case 21537:case 21531:e=P();if(!d.ea.cb)throw new R(59);return d.ea.cb(d,b,e);case 21523:if(!d.ha)return-59;d.ha.sa.gb&&(f=[24,80],e=P(),Fa[e>>1]=f[0],Fa[e+2>>1]=f[1]);return 0;case 21524:return d.ha?0:-59;case 21515:return d.ha?0:-59;default:return-28}}catch(g){if("undefined"==typeof Z||"ErrnoError"!==g.name)throw g;return-g.qa}}
function Za(a,b,c,d){if(l)return L(5,1,a,b,c,d);O=d;try{b=b?Q(t,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":W(a).path;if(0==e.length)throw new R(44);b=f+"/"+e}var g=d?P():0;return Ma(b,c,g).ta}catch(m){if("undefined"==typeof Z||"ErrnoError"!==m.name)throw m;return-m.qa}}
var $a=()=>G(""),ab=a=>{za(a,!k,1,!aa,1048576,!1);Aa()},Mc=a=>{if(a instanceof Pb||"unwind"==a)return x;throw a;},Yb=a=>{if(!Ia&&!qa)try{if(a(),!(Ia||0<K))try{l?Cb()&&Ib(x):sb(x)}catch(b){Mc(b)}}catch(b){Mc(b)}},Ba=a=>{"function"===typeof Atomics.waitAsync&&(Atomics.waitAsync(A,a>>2,a).value.then(Da),Atomics.store(A,a+128>>2,1))},Da=()=>Yb(()=>{var a=Cb();a&&(Ba(a),Kb())}),bb=(a,b)=>{a==b?setTimeout(Da):l?postMessage({Ga:a,pa:"checkMailbox"}):(a=J[a])&&a.postMessage({pa:"checkMailbox"})},Nc=[],cb=
(a,b,c,d,e)=>{d/=2;Nc.length=d;b=e>>3;for(c=0;c<d;c++)Nc[c]=E[b+2*c]?E[b+2*c+1]:Ga[b+2*c+1];return(0,Oc[a])(...Nc)},db=()=>{K=0},eb=a=>{l?postMessage({pa:"cleanupThread",lb:a}):Xb(J[a])},fb=()=>{},Pc=[0,31,60,91,121,152,182,213,244,274,305,335],Qc=[0,31,59,90,120,151,181,212,243,273,304,334];
function gb(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);A[b>>2]=a.getSeconds();A[b+4>>2]=a.getMinutes();A[b+8>>2]=a.getHours();A[b+12>>2]=a.getDate();A[b+16>>2]=a.getMonth();A[b+20>>2]=a.getFullYear()-1900;A[b+24>>2]=a.getDay();var c=a.getFullYear();A[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Qc:Pc)[a.getMonth()]+a.getDate()-1|0;A[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
A[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0}var Rc={},nb=()=>performance.timeOrigin+performance.now();function hb(a,b){if(l)return L(6,1,a,b);Rc[a]&&(clearTimeout(Rc[a].id),delete Rc[a]);if(!b)return 0;var c=setTimeout(()=>{delete Rc[a];Yb(()=>Jb(a,performance.timeOrigin+performance.now()))},b);Rc[a]={id:c,Fb:b};return 0}
var ib=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();B[a>>2]=60*Math.max(f,e);A[b>>2]=Number(f!=e);b=g=>{var m=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(m/60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(r(a,t,c,17),r(b,t,d,17)):(r(a,t,d,17),r(b,t,c,17))},Sc=1;
function jb(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(Sc)a=performance.timeOrigin+performance.now();else return 52;E[c>>3]=BigInt(Math.round(1E6*a));return 0}
var Tc=()=>{Tc.Oa||(Tc.Oa={});Tc.Oa["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(Tc.Oa["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,u("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"))},kb=()=>{k||(Tc(),G("Blocking on the main thread is not allowed by default. See https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"))},
lb=()=>{K+=1;throw"unwind";},mb=(a,b,c)=>{var d=Error().stack.toString(),e=d.split("\n");d="";var f=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),g=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),m;for(m of e){var p=g.exec(m);if(5==p?.length){e=p[1];var n=p[2];var v=p[3];p=p[4]}else if(p=f.exec(m),4<=p?.length)e=p[1],n=p[2],v=p[3],p=p[4]|0;else{d+=m+"\n";continue}"_emscripten_log"==e||"_emscripten_get_callstack"==e?d="":a&24&&(a&64&&(n=n.substring(n.replace(/\\/g,"/").lastIndexOf("/")+1)),d+=`    at ${e} (${n}:${v}:${p})\n`)}a=
d=d.replace(/\s+$/,"");return!b||0>=c?q(a)+1:r(a,t,b,c)+1},ob=()=>{G("OOM")},Uc={},Wc=()=>{if(!Vc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in Uc)void 0===Uc[b]?delete a[b]:a[b]=Uc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Vc=c}return Vc},Vc;
function qb(a,b){if(l)return L(7,1,a,b);var c=0,d=0,e;for(e of Wc()){var f=b+c;B[a+d>>2]=f;c+=r(e,t,f,Infinity)+1;d+=4}return 0}function rb(a,b){if(l)return L(8,1,a,b);var c=Wc();B[a>>2]=c.length;a=0;for(var d of c)a+=q(d)+1;B[b>>2]=a;return 0}function tb(a){if(l)return L(9,1,a);try{var b=W(a);Wb(b);return 0}catch(c){if("undefined"==typeof Z||"ErrnoError"!==c.name)throw c;return c.qa}}
function ub(a,b,c,d){if(l)return L(10,1,a,b,c,d);try{a:{var e=W(a);a=b;for(var f,g=b=0;g<c;g++){var m=B[a>>2],p=B[a+4>>2];a+=8;var n=e,v=m,S=p,C=f,Pa=z;if(0>S||0>C)throw new R(28);if(null===n.ta)throw new R(8);if(1===(n.flags&2097155))throw new R(8);if(16384===(n.node.mode&61440))throw new R(31);if(!n.ea.read)throw new R(28);var ca="undefined"!=typeof C;if(!ca)C=n.position;else if(!n.seekable)throw new R(70);var da=n.ea.read(n,Pa,v,S,C);ca||(n.position+=da);var D=da;if(0>D){var ea=-1;break a}b+=D;
if(D<p)break;"undefined"!=typeof f&&(f+=D)}ea=b}B[d>>2]=ea;return 0}catch(N){if("undefined"==typeof Z||"ErrnoError"!==N.name)throw N;return N.qa}}function vb(a,b,c,d){if(l)return L(11,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=W(a);Lc(e,b,c);E[d>>3]=BigInt(e.position);e.La&&0===b&&0===c&&(e.La=null);return 0}catch(f){if("undefined"==typeof Z||"ErrnoError"!==f.name)throw f;return f.qa}}
function wb(a,b,c,d){if(l)return L(12,1,a,b,c,d);try{a:{var e=W(a);a=b;for(var f,g=b=0;g<c;g++){var m=B[a>>2],p=B[a+4>>2];a+=8;var n=e,v=m,S=p,C=f,Pa=z;if(0>S||0>C)throw new R(28);if(null===n.ta)throw new R(8);if(0===(n.flags&2097155))throw new R(8);if(16384===(n.node.mode&61440))throw new R(31);if(!n.ea.write)throw new R(28);n.seekable&&n.flags&1024&&Lc(n,0,2);var ca="undefined"!=typeof C;if(!ca)C=n.position;else if(!n.seekable)throw new R(70);var da=n.ea.write(n,Pa,v,S,C,void 0);ca||(n.position+=
da);var D=da;if(0>D){var ea=-1;break a}b+=D;if(D<p)break;"undefined"!=typeof f&&(f+=D)}ea=b}B[d>>2]=ea;return 0}catch(N){if("undefined"==typeof Z||"ErrnoError"!==N.name)throw N;return N.qa}}function zb(a,b){try{return hc(t.subarray(a,a+b)),0}catch(c){if("undefined"==typeof Z||"ErrnoError"!==c.name)throw c;return c.qa}}U=Array(4096);Ic(T,"/");X("/tmp");X("/home");X("/home/web_user");
(function(){X("/dev");nc(259,{read:()=>0,write:(d,e,f,g)=>g,la:()=>0});Kc("/dev/null",259);mc(1280,pc);mc(1536,qc);Kc("/dev/tty",1280);Kc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(hc(a),b=a.byteLength);return a[--b]};Y("random",c);Y("urandom",c);X("/dev/shm");X("/dev/shm/tmp")})();
(function(){X("/proc");var a=X("/proc/self");X("/proc/self/fd");Ic({ra(){var b=sc(a,"fd",16895,73);b.ea={la:T.ea.la};b.ga={xa(c,d){c=+d;var e=W(c);c={parent:null,ra:{Ta:"fake"},ga:{ya:()=>e.path},id:c+1};return c.parent=c},Na(){return Array.from(M.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();l||(y=new WebAssembly.Memory({initial:2560,maximum:2560,shared:!0}),va());h.print&&(pa=h.print);h.printErr&&(u=h.printErr);h.callMain=Xc;
h.stringToUTF8=(a,b,c)=>r(a,t,b,c);h.lengthBytesUTF8=q;var Oc=[yb,Vb,cc,Xa,Ya,Za,hb,qb,rb,tb,ub,vb,wb];function xb(a){h.pb(a?Q(t,a):"")}var fa,ja,Cb,ia,ha,Db,Eb,za,Ea,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Ua;function Xc(a=[]){var b=Db;K+=1;a.unshift("./this.program");var c=a.length,d=Nb(4*(c+1)),e=d;a.forEach(g=>{var m=B,p=e>>2,n=q(g)+1,v=Nb(n);r(g,t,v,n);m[p]=v;e+=4});B[e>>2]=0;try{var f=b(c,d);sb(f,!0);return f}catch(g){return Mc(g)}}
function xa(){if(!(0<wc))if(l)ra?.(h),Ja();else{for(var a=Rb;0<a.length;)a.shift()(h);0<wc||(h.calledRun=!0,qa||(Ja(),ra?.(h),h.noInitialRun||Xc(ka)))}}var F;l||(F=await (wa()),xa());Ha?moduleRtn=h:moduleRtn=new Promise((a,b)=>{ra=a;sa=b});
;return moduleRtn}export default Module;var isPthread=globalThis.self?.name?.startsWith("em-pthread");isPthread&&Module();
